# Generated by Django 6.0.2 on 2026-02-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_default',
        ),
    ]
